swagger: "2.0"
info:
  title: Spin API service
  description: HTTP service for controlling the spin service
  version: ""
host: localhost:8080
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /add/{id}:
    post:
      tags:
      - spin-broker
      summary: add spin-broker
      description: Add a command to the package
      operationId: spin-broker#add
      parameters:
      - name: id
        in: path
        description: Package ID
        required: true
        type: string
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinBrokerAddRequestBody'
          required:
          - resource
          - action
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /complete:
    post:
      tags:
      - spin-broker
      summary: complete spin-broker
      description: Mark a command as completed with a result status
      operationId: spin-broker#complete
      parameters:
      - name: CompleteRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinBrokerCompleteRequestBody'
          required:
          - id
          - status
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /control/shutdown/{id}:
    post:
      tags:
      - spin-apiserver
      summary: control_shutdown spin-apiserver
      operationId: spin-apiserver#control_shutdown
      parameters:
      - name: id
        in: path
        description: ID of VM to shutdown
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /control/start/{id}:
    post:
      tags:
      - spin-apiserver
      summary: control_start spin-apiserver
      operationId: spin-apiserver#control_start
      parameters:
      - name: id
        in: path
        description: ID of VM to start
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /control/stop/{id}:
    post:
      tags:
      - spin-apiserver
      summary: control_stop spin-apiserver
      operationId: spin-apiserver#control_stop
      parameters:
      - name: id
        in: path
        description: ID of VM to stop
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /enqueue/{id}:
    post:
      tags:
      - spin-broker
      summary: enqueue spin-broker
      description: Enqueue the package into the various resource queues
      operationId: spin-broker#enqueue
      parameters:
      - name: id
        in: path
        description: Package ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Commodi accusamus veritatis quos.
      schemes:
      - http
  /new:
    post:
      tags:
      - spin-broker
      summary: new spin-broker
      description: Create a new package; a collection of items to join into the queue simultaneously
      operationId: spin-broker#new
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /next/{resource}:
    get:
      tags:
      - spin-broker
      summary: next spin-broker
      description: Get the next command for a given resource
      operationId: spin-broker#next
      parameters:
      - name: resource
        in: path
        description: resource type
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinBrokerNextResponseBody'
            required:
            - uuid
            - resource
            - action
        "400":
          description: No records were found
          schema:
            $ref: '#/definitions/SpinBrokerNextRecordNotFoundResponseBody'
      schemes:
      - http
  /status/{id}:
    get:
      tags:
      - spin-broker
      summary: status spin-broker
      description: Get the status for a package
      operationId: spin-broker#status
      parameters:
      - name: id
        in: path
        description: Package ID
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinBrokerStatusResponseBody'
            required:
            - status
        "400":
          description: No records were found
          schema:
            $ref: '#/definitions/SpinBrokerStatusRecordNotFoundResponseBody'
      schemes:
      - http
  /storage/images/create:
    post:
      tags:
      - spin-registry
      summary: storage_images_create spin-registry
      description: add an image definition to the registry
      operationId: spin-registry#storage_images_create
      parameters:
      - name: storage_images_create_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryStorageImagesCreateRequestBody'
          required:
          - image
          - cdrom
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinRegistryStorageImagesCreateResponseBody'
            required:
            - path
            - cdrom
      schemes:
      - http
  /storage/images/delete:
    post:
      tags:
      - spin-registry
      summary: storage_images_delete spin-registry
      description: remove an image definition from the registry
      operationId: spin-registry#storage_images_delete
      parameters:
      - name: storage_images_delete_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryStorageImagesDeleteRequestBody'
          required:
          - volume_name
          - image_name
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /storage/images/get:
    get:
      tags:
      - spin-registry
      summary: storage_images_get spin-registry
      description: retrieves an image definition from the registry
      operationId: spin-registry#storage_images_get
      parameters:
      - name: storage_images_get_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryStorageImagesGetRequestBody'
          required:
          - volume_name
          - image_name
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinRegistryStorageImagesGetResponseBody'
            required:
            - path
            - cdrom
      schemes:
      - http
  /storage/images/list:
    get:
      tags:
      - spin-registry
      summary: storage_images_list spin-registry
      description: list all images by volume
      operationId: spin-registry#storage_images_list
      parameters:
      - name: storage_images_list_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryStorageImagesListRequestBody'
          required:
          - volume_name
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: string
              example: Corporis nam.
      schemes:
      - http
  /storage/volumes/create:
    post:
      tags:
      - spin-registry
      summary: storage_volumes_create spin-registry
      description: create a new volume
      operationId: spin-registry#storage_volumes_create
      parameters:
      - name: storage_volumes_create_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryStorageVolumesCreateRequestBody'
          required:
          - name
          - path
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /storage/volumes/delete:
    post:
      tags:
      - spin-registry
      summary: storage_volumes_delete spin-registry
      description: delete an existing volume
      operationId: spin-registry#storage_volumes_delete
      parameters:
      - name: storage_volumes_delete_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryStorageVolumesDeleteRequestBody'
          required:
          - name
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /storage/volumes/list:
    get:
      tags:
      - spin-registry
      summary: storage_volumes_list spin-registry
      description: list all volumes
      operationId: spin-registry#storage_volumes_list
      responses:
        "200":
          description: OK response.
          schema:
            type: object
            additionalProperties: true
      schemes:
      - http
  /vm/create:
    post:
      tags:
      - spin-registry
      summary: vm_create spin-registry
      description: Create a VM
      operationId: spin-registry#vm_create
      parameters:
      - name: vm_create_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryVMCreateRequestBody'
          required:
          - name
          - cpus
          - memory
          - images
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
      schemes:
      - http
  /vm/delete/{id}:
    post:
      tags:
      - spin-registry
      summary: vm_delete spin-registry
      description: Delete a VM by ID
      operationId: spin-registry#vm_delete
      parameters:
      - name: id
        in: path
        description: ID of VM to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /vm/get/{id}:
    get:
      tags:
      - spin-registry
      summary: vm_get spin-registry
      description: Retrieve a VM by ID
      operationId: spin-registry#vm_get
      parameters:
      - name: id
        in: path
        description: ID of VM to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SpinRegistryVMGetResponseBody'
            required:
            - name
            - cpus
            - memory
            - images
      schemes:
      - http
  /vm/list:
    get:
      tags:
      - spin-registry
      summary: vm_list spin-registry
      description: Retrieve all VM IDs
      operationId: spin-registry#vm_list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: integer
              example: 11055455870090139273
              format: int64
      schemes:
      - http
    post:
      tags:
      - spin-apiserver
      summary: vm_list spin-apiserver
      operationId: spin-apiserver#vm_list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              type: integer
              example: 16162782905924696272
              format: int64
      schemes:
      - http
  /vm/update/{id}:
    post:
      tags:
      - spin-registry
      summary: vm_update spin-registry
      description: Update a VM
      operationId: spin-registry#vm_update
      parameters:
      - name: id
        in: path
        description: ID of VM to update
        required: true
        type: integer
      - name: vm_update_request_body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SpinRegistryVMUpdateRequestBody'
          required:
          - vm
      responses:
        "200":
          description: OK response.
      schemes:
      - http
definitions:
  ImageRequestBody:
    title: ImageRequestBody
    type: object
    properties:
      cdrom:
        type: boolean
        description: Is this a cdrom image?
        example: true
      path:
        type: string
        description: Image path
        example: Doloremque et iusto.
      volume:
        type: string
        description: Volume name
        example: Similique aliquid corrupti amet numquam sed totam.
    example:
      cdrom: false
      path: Minima omnis.
      volume: Ut quidem aut et qui.
    required:
    - path
    - cdrom
  ImageResponseBody:
    title: ImageResponseBody
    type: object
    properties:
      cdrom:
        type: boolean
        description: Is this a cdrom image?
        example: false
      path:
        type: string
        description: Image path
        example: Veritatis aut architecto deleniti incidunt.
      volume:
        type: string
        description: Volume name
        example: Tempora quisquam inventore inventore qui nihil.
    example:
      cdrom: false
      path: Natus consectetur.
      volume: Et nesciunt et molestiae.
    required:
    - path
    - cdrom
  SpinApiserverVMCreateRequestBody:
    title: SpinApiserverVMCreateRequestBody
    type: object
    properties:
      cpus:
        type: integer
        description: CPU count
        example: 827813068308857193
        format: int64
      memory:
        type: integer
        description: Memory (in megabytes)
        example: 2639635305187102420
        format: int64
      name:
        type: string
        description: Name of VM; does not need to be unique
        example: Veniam soluta eum laudantium.
      ports:
        type: object
        description: 'Ports to map to this vm: guest -> host addr:port'
        example:
          13249802869037512027: Qui ad aut possimus quisquam harum.
        additionalProperties: true
      storage:
        type: array
        items:
          $ref: '#/definitions/StorageRequestBody'
        description: Storage references
        example:
        - cdrom: false
          image: Esse labore voluptas.
          image_size: 4373530742914524004
          volume: Rerum porro eius.
        - cdrom: false
          image: Esse labore voluptas.
          image_size: 4373530742914524004
          volume: Rerum porro eius.
        - cdrom: false
          image: Esse labore voluptas.
          image_size: 4373530742914524004
          volume: Rerum porro eius.
    example:
      cpus: 16743863857589963181
      memory: 9222926294244299631
      name: Natus quasi quia vel ut.
      ports:
        6037338872195264093: Quos vel in modi rerum.
      storage:
      - cdrom: false
        image: Esse labore voluptas.
        image_size: 4373530742914524004
        volume: Rerum porro eius.
      - cdrom: false
        image: Esse labore voluptas.
        image_size: 4373530742914524004
        volume: Rerum porro eius.
      - cdrom: false
        image: Esse labore voluptas.
        image_size: 4373530742914524004
        volume: Rerum porro eius.
    required:
    - name
    - cpus
    - memory
    - storage
  SpinApiserverVMGetResponseBody:
    title: SpinApiserverVMGetResponseBody
    type: object
    properties:
      cpus:
        type: integer
        description: CPU count
        example: 6630383005671600344
        format: int64
      images:
        type: array
        items:
          $ref: '#/definitions/ImageResponseBody'
        description: Image references
        example:
        - cdrom: false
          path: Assumenda pariatur.
          volume: Nobis quia.
        - cdrom: false
          path: Assumenda pariatur.
          volume: Nobis quia.
      memory:
        type: integer
        description: Memory (in megabytes)
        example: 8629926544877524812
        format: int64
      name:
        type: string
        description: Name of VM; does not need to be unique
        example: Animi dolorem totam omnis molestiae voluptatum rerum.
      ports:
        type: object
        description: 'Ports to map to this vm: guest -> host addr:port'
        example:
          15250316450076326828: Voluptatem est.
        additionalProperties: true
    example:
      cpus: 710111403244910451
      images:
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      memory: 8901734024100363251
      name: Blanditiis consequatur consequuntur praesentium consequatur.
      ports:
        6724682511515004255: Accusantium labore.
        7027084381674330812: Consequuntur tempora dolorem quibusdam minus.
        10331482834864607323: Ab nulla quis exercitationem voluptatem.
    required:
    - name
    - cpus
    - memory
    - images
  SpinApiserverVMUpdateRequestBody:
    title: SpinApiserverVMUpdateRequestBody
    type: object
    properties:
      vm:
        $ref: '#/definitions/UpdatedVMRequestBody'
    example:
      vm:
        cpus: 1235757894805898603
        images:
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        memory: 11516433357545643392
        name: Rerum asperiores corporis aut.
        ports:
          8213131886962674554: Maxime est voluptatem quia.
    required:
    - vm
  SpinBrokerAddRequestBody:
    title: SpinBrokerAddRequestBody
    type: object
    properties:
      action:
        type: string
        description: Action name
        example: Exercitationem incidunt quae est velit eaque mollitia.
      dependencies:
        type: array
        items:
          type: string
          example: Qui ea qui omnis qui sit et.
        description: Dependency UUIDs
        example:
        - Enim ut voluptas ullam quas aliquam.
        - Quaerat illo molestiae.
        - Cupiditate perspiciatis voluptas quia.
        - Adipisci et provident.
      parameters:
        type: object
        description: Action parameters
        example:
          Similique qui qui.: Minima nemo omnis quia deleniti.
        additionalProperties: true
      resource:
        type: string
        description: Resource name
        example: Quia ut laboriosam beatae itaque omnis.
    example:
      action: Qui sit nihil.
      dependencies:
      - Aperiam impedit autem.
      - Ut quidem numquam provident occaecati animi saepe.
      parameters:
        Commodi placeat exercitationem nostrum est totam.: Eligendi quod voluptas sed.
        Repudiandae eos.: Quibusdam error dolorem.
        Sequi voluptatem culpa unde ut.: Aut ut illum.
      resource: Ea iusto modi aspernatur.
    required:
    - resource
    - action
  SpinBrokerCompleteRequestBody:
    title: SpinBrokerCompleteRequestBody
    type: object
    properties:
      id:
        type: string
        description: Command ID
        example: Voluptas non officiis.
      status:
        type: boolean
        description: status of work
        example: true
      status_reason:
        type: string
        description: reason of success/failure
        example: Quia quisquam hic est quisquam.
    example:
      id: Quae incidunt nulla sit.
      status: true
      status_reason: Voluptas dolorem.
    required:
    - id
    - status
  SpinBrokerNextRecordNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: next_record_not_found_response_body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  SpinBrokerNextResponseBody:
    title: SpinBrokerNextResponseBody
    type: object
    properties:
      action:
        type: string
        description: action name
        example: Et inventore.
      parameters:
        type: object
        description: Action parameters
        example:
          Deserunt dicta eaque reiciendis autem.: Accusamus esse blanditiis.
          Repellendus voluptate voluptas.: In inventore.
          Sequi temporibus.: Inventore cupiditate commodi aut asperiores quidem sit.
        additionalProperties: true
      resource:
        type: string
        description: resource type
        example: Aliquid blanditiis repudiandae adipisci accusantium consequuntur.
      uuid:
        type: string
        description: Command ID
        example: Eum officiis sit quis itaque ducimus qui.
    example:
      action: Officia animi fugiat excepturi sed nisi aut.
      parameters:
        Quae illum.: Voluptates natus neque qui iusto ex et.
        Saepe in repudiandae reiciendis eveniet repudiandae.: Perferendis impedit.
      resource: At sed necessitatibus et asperiores earum hic.
      uuid: Deleniti cum repudiandae veniam vel provident.
    required:
    - uuid
    - resource
    - action
  SpinBrokerStatusRecordNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: status_record_not_found_response_body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  SpinBrokerStatusResponseBody:
    title: SpinBrokerStatusResponseBody
    type: object
    properties:
      causer:
        type: string
        description: Failure causer as UUID (if any)
        example: In animi quos voluptatem qui explicabo.
      reason:
        type: string
        description: Failure reason (if any)
        example: Quisquam ex officia voluptas voluptate.
      status:
        type: boolean
        description: Pass/Fail status
        example: true
    example:
      causer: Qui sint delectus quis.
      reason: Voluptatum deleniti maxime possimus vero omnis.
      status: false
    required:
    - status
  SpinRegistryStorageImagesCreateRequestBody:
    title: SpinRegistryStorageImagesCreateRequestBody
    type: object
    properties:
      cdrom:
        type: boolean
        description: Is this image a cdrom?
        example: false
      image:
        type: string
        description: Image filename, no `/` characters
        example: Molestias officiis accusamus rerum facilis.
      image_size:
        type: integer
        description: Image size (in gigabytes); required if image is not a cdrom
        example: 6936064503355869647
        format: int64
      volume:
        type: string
        description: Volume name; required if image is not a cdrom
        example: Illo eos repudiandae et vel corporis.
    example:
      cdrom: false
      image: Voluptas et omnis enim.
      image_size: 12004874832024600777
      volume: Placeat odio ea et minima cum.
    required:
    - image
    - cdrom
  SpinRegistryStorageImagesCreateResponseBody:
    title: SpinRegistryStorageImagesCreateResponseBody
    type: object
    properties:
      cdrom:
        type: boolean
        description: Is this a cdrom image?
        example: false
      path:
        type: string
        description: Image path
        example: Expedita voluptatem reiciendis voluptatem dicta.
      volume:
        type: string
        description: Volume name
        example: Qui ipsa et magnam sed.
    example:
      cdrom: true
      path: Quam non.
      volume: Distinctio eveniet assumenda temporibus a.
    required:
    - path
    - cdrom
  SpinRegistryStorageImagesDeleteRequestBody:
    title: SpinRegistryStorageImagesDeleteRequestBody
    type: object
    properties:
      image_name:
        type: string
        description: name of image
        example: Tempora fugit qui doloremque.
      volume_name:
        type: string
        description: name of volume
        example: Reprehenderit dolorum non qui.
    example:
      image_name: Facere reprehenderit consequuntur inventore reiciendis tempora est.
      volume_name: Eius corporis occaecati aut adipisci.
    required:
    - volume_name
    - image_name
  SpinRegistryStorageImagesGetRequestBody:
    title: SpinRegistryStorageImagesGetRequestBody
    type: object
    properties:
      image_name:
        type: string
        description: name of image
        example: Repellat cupiditate odit commodi veniam corrupti.
      volume_name:
        type: string
        description: name of volume
        example: Veniam fugit in.
    example:
      image_name: Molestiae voluptatem quos inventore aut.
      volume_name: Consequatur eos aut laborum at.
    required:
    - volume_name
    - image_name
  SpinRegistryStorageImagesGetResponseBody:
    title: SpinRegistryStorageImagesGetResponseBody
    type: object
    properties:
      cdrom:
        type: boolean
        description: Is this a cdrom image?
        example: false
      path:
        type: string
        description: Image path
        example: Et quia consequatur magnam officia.
      volume:
        type: string
        description: Volume name
        example: Vel ipsum autem et et placeat.
    example:
      cdrom: false
      path: Officiis velit hic unde assumenda praesentium.
      volume: Eum nihil dicta optio.
    required:
    - path
    - cdrom
  SpinRegistryStorageImagesListRequestBody:
    title: SpinRegistryStorageImagesListRequestBody
    type: object
    properties:
      volume_name:
        type: string
        description: name of volume to list images for
        example: Deserunt modi qui voluptatem placeat.
    example:
      volume_name: Ullam dolore ea at ut.
    required:
    - volume_name
  SpinRegistryStorageVolumesCreateRequestBody:
    title: SpinRegistryStorageVolumesCreateRequestBody
    type: object
    properties:
      name:
        type: string
        description: name of volume
        example: Quis sed voluptas omnis.
      path:
        type: string
        description: path to volume
        example: Qui quibusdam odio est nulla eum.
    example:
      name: Cupiditate neque eos aperiam.
      path: Sunt doloremque.
    required:
    - name
    - path
  SpinRegistryStorageVolumesDeleteRequestBody:
    title: SpinRegistryStorageVolumesDeleteRequestBody
    type: object
    properties:
      name:
        type: string
        description: name of volume
        example: Sint ut perspiciatis.
    example:
      name: Quos maxime ut error facilis modi autem.
    required:
    - name
  SpinRegistryVMCreateRequestBody:
    title: SpinRegistryVMCreateRequestBody
    type: object
    properties:
      cpus:
        type: integer
        description: CPU count
        example: 7960362848282598736
        format: int64
      images:
        type: array
        items:
          $ref: '#/definitions/ImageRequestBody'
        description: Image references
        example:
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
      memory:
        type: integer
        description: Memory (in megabytes)
        example: 696022035535720389
        format: int64
      name:
        type: string
        description: Name of VM; does not need to be unique
        example: Fugit adipisci aliquid aliquam.
      ports:
        type: object
        description: 'Ports to map to this vm: guest -> host addr:port'
        example:
          4047906078158329845: Est quia nemo suscipit alias.
          5522998880503880554: Aliquam nobis dicta dignissimos optio quisquam.
        additionalProperties: true
    example:
      cpus: 6521501625636069185
      images:
      - cdrom: true
        path: Explicabo sit ab.
        volume: Quis quidem nulla.
      - cdrom: true
        path: Explicabo sit ab.
        volume: Quis quidem nulla.
      - cdrom: true
        path: Explicabo sit ab.
        volume: Quis quidem nulla.
      - cdrom: true
        path: Explicabo sit ab.
        volume: Quis quidem nulla.
      memory: 8803024106508117673
      name: Ut id aut dolores.
      ports:
        17656810983404926439: Nisi placeat quasi consequatur ut sed.
    required:
    - name
    - cpus
    - memory
    - images
  SpinRegistryVMGetResponseBody:
    title: SpinRegistryVMGetResponseBody
    type: object
    properties:
      cpus:
        type: integer
        description: CPU count
        example: 6381698118855045955
        format: int64
      images:
        type: array
        items:
          $ref: '#/definitions/ImageResponseBody'
        description: Image references
        example:
        - cdrom: false
          path: Assumenda pariatur.
          volume: Nobis quia.
        - cdrom: false
          path: Assumenda pariatur.
          volume: Nobis quia.
        - cdrom: false
          path: Assumenda pariatur.
          volume: Nobis quia.
      memory:
        type: integer
        description: Memory (in megabytes)
        example: 11692559188285813327
        format: int64
      name:
        type: string
        description: Name of VM; does not need to be unique
        example: Ut modi sint quo.
      ports:
        type: object
        description: 'Ports to map to this vm: guest -> host addr:port'
        example:
          3030823960754760868: Ut optio nemo.
          4375529905132579729: Libero ea repudiandae.
        additionalProperties: true
    example:
      cpus: 17106812839344055104
      images:
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      - cdrom: false
        path: Assumenda pariatur.
        volume: Nobis quia.
      memory: 18276940718251142926
      name: Similique eligendi veniam.
      ports:
        4958259689897901043: Unde sed commodi.
        7636634391002491891: Voluptas laborum.
        13898844425479384601: Ipsum minima fugit vero.
    required:
    - name
    - cpus
    - memory
    - images
  SpinRegistryVMUpdateRequestBody:
    title: SpinRegistryVMUpdateRequestBody
    type: object
    properties:
      vm:
        $ref: '#/definitions/UpdatedVMRequestBody'
    example:
      vm:
        cpus: 1235757894805898603
        images:
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        memory: 11516433357545643392
        name: Rerum asperiores corporis aut.
        ports:
          8213131886962674554: Maxime est voluptatem quia.
    required:
    - vm
  StorageRequestBody:
    title: StorageRequestBody
    type: object
    properties:
      cdrom:
        type: boolean
        description: Is this image a cdrom?
        example: true
      image:
        type: string
        description: Image filename, no `/` characters
        example: Rerum odit.
      image_size:
        type: integer
        description: Image size (in gigabytes); required if image is not a cdrom
        example: 3731676477825233066
        format: int64
      volume:
        type: string
        description: Volume name; required if image is not a cdrom
        example: Corporis quo.
    example:
      cdrom: false
      image: Officiis perspiciatis.
      image_size: 12097151193832539624
      volume: Fugiat sapiente sequi molestiae inventore aut.
    required:
    - image
    - cdrom
  UpdatedVMRequestBody:
    title: UpdatedVMRequestBody
    type: object
    properties:
      cpus:
        type: integer
        description: CPU count
        example: 1715928827592478753
        format: int64
      images:
        type: array
        items:
          $ref: '#/definitions/ImageRequestBody'
        description: Image references
        example:
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
        - cdrom: true
          path: Explicabo sit ab.
          volume: Quis quidem nulla.
      memory:
        type: integer
        description: Memory (in megabytes)
        example: 3574204186687680349
        format: int64
      name:
        type: string
        description: Name of VM; does not need to be unique
        example: Labore accusantium ut itaque odio explicabo perferendis.
      ports:
        type: object
        description: 'Ports to map to this vm: guest -> host addr:port'
        example:
          16613239315514824321: Adipisci tempora.
        additionalProperties: true
    example:
      cpus: 5691607402281797891
      images:
      - cdrom: true
        path: Explicabo sit ab.
        volume: Quis quidem nulla.
      - cdrom: true
        path: Explicabo sit ab.
        volume: Quis quidem nulla.
      memory: 5917043672075731270
      name: Id rerum hic.
      ports:
        3984617861639826381: Odio quia voluptas deserunt.
        9507820352880056900: Illum enim sequi soluta omnis deleniti autem.
        11438016409281173653: Dignissimos nihil soluta necessitatibus voluptas.
    required:
    - name
    - cpus
    - memory
    - images
